volumes:
  {{repository_name}}-node-modules:

services:
  {{repository_name}}-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/app:/app
      - {{repository_name}}-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - {{repository_name}}-app-network

networks:
  {{repository_name}}-app-network:
    driver: bridge